# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-10 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='lease_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='lease_start_date',
            field=models.DateField(null=True),
        ),
    ]
