# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_app', '0004_auto_20170920_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='lease_end_date',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='lease_start_date',
            field=models.DateTimeField(max_length=30, null=True),
        ),
    ]
